"""
watt programming API

This file includes everything needed to write programs for watt.
"""

class WattProgram(object):
    """
    Base class program
    All programs must inherit this class in order to be detected (watt detects
    all subclasses in the path).
    """
    name = None
    bpm = None
    beats = None
    measures = None
    commands = {}

class Effect(object):
    """ Type of effect generated by the pedal """
    shallowDetune = 0
    deepDetune = 1
    up2Octaves = 2
    upOctave = 3
    downOctave = 4
    down2Octaves = 5
    diveBomb = 6
    dropTune = 7
    up2ndUp3rd = 8
    upm3rdUp3rd = 9
    up3rdUp4th = 10
    up4thUp5th = 11
    up5thUp6th = 12
    up5thUp7th = 13
    down4thDown3rd = 14
    down5thDown4th = 15
    downOctaveUpOctave = 16
    effect_range = range(shallowDetune, downOctaveUpOctave + 1)

# state of stomp switch
STOMP_ENABLE = 127
STOMP_BYPASS = 0

# state of toe rocker
FWD = 127
BACK = 0

# Intervals
MUTE = 'mute'
P1 = 'P1'

# up
MIN2 = 'm2'
MAJ2 = 'M2'
MIN3 = 'm3'
MAJ3 = 'M3'
P4 = 'P4'
AUG4 = DIM5 = 'A4'
P5 = 'P5'
MIN6 = 'm6'
MAJ6 = 'M6'
MIN7 = 'm7'
MAJ7 = 'M7'
P8 = 'P8'
MIN9 = 'm9'
MAJ9 = 'M9'
MIN10 = 'm10'
MAJ10 = 'M10'
P11 = 'P11'
AUG11 = DIM12 = 'A11'
P12 = 'P12'
MIN13 = 'm13'
MAJ13 = 'M13'
MIN14 = 'm14'
MAJ14 = 'M14'
P15 = 'P15'

# down
D_MIN2 = 'Dm2'
D_MAJ2 = 'DM2'
D_MIN3 = 'Dm3'
D_MAJ3 = 'DM3'
D_P4 = 'DP4'
D_AUG4 = D_DIM5 = 'DA4'
D_P5 = 'DP5'
D_MIN6 = 'Dm6'
D_MAJ6 = 'DM6'
D_MIN7 = 'Dm7'
D_MAJ7 = 'DM7'
D_P8 = 'DP8'
D_MIN9 = 'Dm9'
D_MAJ9 = 'DM9'
D_MIN10 = 'Dm10'
D_MAJ10 = 'DM10'
D_P11 = 'DP11'
D_AUG11 = D_DIM12 = 'DA11'
D_P12 = 'DP12'
D_MIN13 = 'Dm13'
D_MAJ13 = 'DM13'
D_MIN14 = 'Dm14'
D_MAJ14 = 'DM14'
D_P15 = 'DP15'
D_MIN16 = 'Dm16'
D_MAJ16 = 'DM16'
D_MIN17 = 'Dm17'
D_MAJ17 = 'DM17'
D_P18 = 'DP18'
D_AUG18 = D_DIM19 = 'DA18'
D_P19 = 'DP19'
D_MIN20 = 'Dm20'
D_MAJ20 = 'DM20'
D_MIN21 = 'Dm21'
D_MAJ21 = 'DM21'
D_P22 = 'DP22'

# scales
CHROMATIC = [D_P22, D_MAJ21, D_MIN21, D_MAJ20, D_MIN20, D_P19, D_AUG18, D_P18,
             D_MAJ17, D_MIN17, D_MAJ16, D_MIN16,
             D_P15, D_MAJ14, D_MIN14, D_MAJ13, D_MIN13, D_P12, D_AUG11, D_P11,
             D_MAJ10, D_MIN10, D_MAJ9, D_MIN9, D_P8, D_MAJ7, D_MIN7, D_MAJ6,
             D_MIN6, D_P5, D_AUG4, D_P4, D_MAJ3, D_MIN3, D_MAJ2, D_MIN2,
             P1, MIN2, MAJ2, MIN3, MAJ3, P4, AUG4, P5, MIN6, MAJ6, MIN7, MAJ7,
             P8, MIN9, MAJ9, MIN10, MAJ10, P11, AUG11, P12, MIN13, MAJ13,
             MIN14, MAJ14, P15]

IONIAN = MAJOR_SCALE = [P1, MAJ2, MAJ3, P4, P5, MAJ6, MAJ7, P8]
DORIAN = MINOR_SCALE = [P1, MAJ2, MIN3, P4, P5, MAJ6, MIN7, P8]
PHRYGIAN = [P1, MIN2, MIN3, P4, P5, MIN6, MIN7, P8]
LYDIAN = [P1, MAJ2, MAJ3, AUG4, P5, MAJ6, MAJ7, P8]
MIXOLYDIAN = [P1, MAJ2, MAJ3, P4, P5, MAJ6, MIN7, P8]
AEOLIAN = [P1, MAJ2, MIN3, P4, P5, MIN6, MIN7, P8]
LOCRIAN = [P1, MIN2, MIN3, P4, DIM5, MIN6, MIN7, P8]
MODES = [IONIAN,
         DORIAN,
         PHRYGIAN,
         LYDIAN,
         MIXOLYDIAN,
         AEOLIAN,
         LOCRIAN,
        ]
WHOLETONE = [P1, MAJ2, MAJ3, AUG4, MIN6, MIN6, P8]
PENTATONIC = [P1, MIN3, P4, P5, MIN7, P8]

# A map of the intervals that can be generated with each effect to the toe
# values that generates them
INTERVAL_MAP = {
    Effect.shallowDetune: {
        P1: 0
    },
    Effect.deepDetune: {
        P1: 0
    },
    Effect.up2Octaves: {
        P1: 0, MIN2: 3, MAJ2: 5, MIN3: 8, MAJ3: 11, P4: 14, AUG4: 18,
        P5: 21, MIN6: 25, MAJ6: 29, MIN7: 33, MAJ7: 38, P8: 43,
        MIN9: 48, MAJ9: 53, MIN10: 59, MAJ10: 65, P11: 71, AUG11: 78,
        P12: 85, MIN13: 93, MAJ13: 101, MIN14: 110, MAJ14: 119, P15: 127
    },
    Effect.upOctave: {
        P1: 0, MIN2: 8, MAJ2: 16, MIN3: 25, MAJ3: 34, P4: 43, AUG4: 53,
        P5: 64, MIN6: 76, MAJ6: 88, MIN7: 100, MAJ7: 114, P8: 127,
    },
    Effect.downOctave : {
        P1: 0, D_MIN2: 14, D_MAJ2: 28, D_MIN3: 41, D_MAJ3: 53, D_P4: 64,
        D_AUG4: 75, D_P5: 85, D_MIN6: 95, D_MAJ6: 104, D_MIN7: 112, D_MAJ7: 120,
        D_P8: 127,
    },
    Effect.down2Octaves : {
        P1: 0, D_MIN2: 9, D_MAJ2: 18, D_MIN3: 27, D_MAJ3: 35, D_P4: 43,
        D_AUG4: 50, D_P5: 57, D_MIN6: 63, D_MAJ6: 69, D_MIN7: 75, D_MAJ7: 80,
        D_P8: 85, D_MIN9: 90, D_MAJ9: 95, D_MIN10: 99, D_MAJ10: 103, D_P11: 107,
        D_AUG11: 110, D_P12: 114, D_MIN13: 117, D_MAJ13: 120, D_MIN14: 123,
        D_MAJ14: 125, D_P15: 127
    },
    Effect.diveBomb: {
        P1: 0, D_MIN2: 8, D_MAJ2: 16, D_MIN3: 23, D_MAJ3: 30, D_P4: 37,
        D_AUG4: 43, D_P5: 49, D_MIN6: 54, D_MAJ6: 59, D_MIN7: 64, D_MAJ7: 69,
        D_P8: 73, D_MIN9: 77, D_MAJ9: 81, D_MIN10: 85, D_MAJ10: 88, D_P11: 91,
        D_AUG11: 94, D_P12: 97, D_MIN13: 100, D_MAJ13: 103, D_MIN14: 105,
        D_MAJ14: 108, D_P15: 110, D_MIN16: 112, D_MAJ16: 114, D_MIN17: 115,
        D_MAJ17: 117, D_P18: 119, D_AUG18: 120, D_P19: 122, D_MIN20: 123,
        D_MAJ20: 124, D_MIN21: 126, D_MAJ21: 127, D_P22: 127, MUTE: 127
    },
    Effect.dropTune: {
        P1: 0
    },
    Effect.downOctaveUpOctave: {
    },
    Effect.down5thDown4th: {
    },
    Effect.down4thDown3rd: {
    },
    Effect.up5thUp7th: {
    },
    Effect.up5thUp6th: {
    },
    Effect.up4thUp5th: {
    },
    Effect.up3rdUp4th: {
    },
    Effect.up2ndUp3rd: {
    },
}
